### ISSUE TITLE
Cannot generate openapi client with swagger/openapi-generator

### ISSUE THREAD

**Issue by dpalic** [d-yoshi/redmine-openapi#1]
using maven

```
            <!-- https://mvnrepository.com/artifact/org.openapitools/openapi-generator-maven-plugin -->
            <plugin>
               <groupId>org.openapitools</groupId>
               <artifactId>openapi-generator-maven-plugin</artifactId>
               <version>7.0.0</version>
               <executions>
                  <execution>
                     <goals>
                        <goal>generate</goal>
                     </goals>
                     <configuration>
                        <inputSpec>https://d-yoshi.github.io/redmine-openapi/openapi.yml</inputSpec>
                        <generatorName>java</generatorName>
                        <library>resttemplate</library>
                        <apiPackage>${openApiPackage}</apiPackage>
                        <modelPackage>${openApiModelPackage}</modelPackage>
                        <useSpringBoot3>true</useSpringBoot3>
                        <generateApis>true</generateApis>
                        <generateApiDocumentation>false</generateApiDocumentation>
                        <generateApiTests>true</generateApiTests>
                        <generateModels>true</generateModels>
                        <generateModelDocumentation>true</generateModelDocumentation>
                        <generateModelTests>false</generateModelTests>
                        <generateSupportingFiles>true</generateSupportingFiles>
                        <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                        <configOptions>
                           <delegatePattern>true</delegatePattern>
                           <additionalModelTypeAnnotations>@lombok.Data</additionalModelTypeAnnotations>
                        </configOptions>
                     </configuration>
                  </execution>
               </executions>
            </plugin>

```

I am getting on the generated classes this compile errors:

SearchFormatGetAttachmentsParameter

`OneOfstringinteger cannot be resolved to a type	SearchFormatGetAttachmentsParameter.java`

so looks like the oneOf definition is still not supported by openapi-generator (since nearly over 3y).
So do you have an idea how to fix this generation issue?

**Comment by dpalic** [comment]
some weeks passed, we have narrowed down the location of the issue

https://github.com/d-yoshi/redmine-openapi/blob/main/openapi.yml#L2399C1-L2408C28

this is messing up the generation into

```
public enum SearchFormatGetAttachmentsParameter {
  
  _0("0"),
  
  _1("1"),
  
  ONLY("only");

  private OneOfstringinteger value; // FIXME: compile error since class OneOfstringinteger cannot be found

  SearchFormatGetAttachmentsParameter(OneOfstringinteger value) {
    this.value = value;
  }

  @JsonValue
  public OneOfstringinteger getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SearchFormatGetAttachmentsParameter fromValue(OneOfstringinteger value) {
    for (SearchFormatGetAttachmentsParameter b : SearchFormatGetAttachmentsParameter.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
```

Any idea how to solve that issue?

A workaround for me is to replace the code with

```
        - name: attachments
          in: query
          schema:
            type: string
            enum:
              - 0
              - 1
              - only

```

but API is now different

**Comment by MatMarrr** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
discoweasel, @bweigel, @torerikaskildsen, @reiallenramos, @ymzkryo, @ycyang1229, @kei-q, @charlychiu, @bkhablenko, @Songs0fFailure, @leogregianin, @archever, @andrewgazelka, @thedrow, @nvinc, @LifeIsAlsoGG, @up4, @Psycadelik, @nakatest1234, @mavaddat, @willfaught, @agentbond007, @devendradate, @ngxk, @tjkemper, @sophiehi, @hboon, @shadow973, @jonarnt, @deraru, @cubaraphael, @rbaulin, @haptibot, @xiabee, @CrossfireCurt, @rwuttke, @gulliverwaite, @gildardoperez, @kobusan, @lior-amsalem, @herlon214, @ju-arroyom, @atdaemon, @CaioCavalcanti, @orca-zhang, @NOLFXceptMe, @davidaparicio, @angelofenoglio, @rkly, @yujieccc

**Comment by d-yoshi** [comment]
You can try this if you still need it.
https://github.com/d-yoshi/redmine-openapi/tree/redmine-5.0.x/v0.2.0
